completion_mode = "circular"
history_size = 500000
max_history_size = 500000
history_duplicates = "ignoreconsecutive"
use_starship = true

path = [
    "/usr/local/opt/tomcat@8/bin",
    "/usr/local/opt/php@7.3/sbin",
    "/usr/local/opt/php@7.3/bin",
    "/usr/local/opt/node@12/bin",
    "/Users/rmcquen/bin",
    "/Users/rmcquen/.cargo/bin",
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin",
    "/Library/Apple/usr/bin"
]
